### ISSUE TITLE
Setting unknown property: kartik\datecontrol\DateControl::field

### ISSUE THREAD

**Issue by ua0leg** [kartik-v/yii2-datecontrol#111]
Hi Kartik,

After yii2 update to 2.0.11.2 i got issue with using DateControl widget.
In a view file:
`use kartik\datecontrol\DateControl;`
`
echo $form->field($model, 'date')->widget(DateControl::class, [
            'type'=>DateControl::FORMAT_DATETIME
        ]);
`

Actually i got this Fatal Error:

`Fatal error: Uncaught exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: kartik\datecontrol\DateControl::field' in /var/www/site/vendor/yiisoft/yii2/base/Component.php:197 Stack trace: #0 /var/www/site/vendor/yiisoft/yii2/BaseYii.php(521): yii\base\Component->__set('field', Object(yii\widgets\ActiveField)) #1 /var/www/site/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(kartik\datecontrol\DateControl), Array) #2 [internal function]: yii\base\Object->__construct(Array) #3 /var/www/site/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array) #4 /var/www/site/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('kartik\\datecont...', Array, Array) #5 /var/www/site/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('kartik\\datecont...', Array, Array) #6 /var/www/site in /var/www/site/vendor/yiisoft/yii2/base/Component.php on line 197`

## Environment
yii2 2.0.11.2
PHP Version 5.6.30-0+deb8u1

#### Libraries

- jQuery version: 2.2.4
- yii2-datecontrol version: 1.9.6

**Comment by ua0leg** [comment]
After reinstalling framework the Error is gone. Maybe it will help someone.
